name: CI

on:
  push:
    branches:
      - main

jobs:
  simple_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Testing 
        echo and testing some more